### ISSUE TITLE
Null pointer exception

### ISSUE THREAD

**Issue by robbydee** [unsound/hfsexplorer#11]
Whenever I try to extract files to a folder that eixsts (or not) I get a null pointer exception

**Comment by unsound** [comment]
This is way too little information to investigate. This is an issue reporter, not a help forum. Please take the time to at least capture a screenshot or copy/paste the text of the error message.

In addition any output in the debug console (File->Debug console) or terminal (if run from the command line) should be included.

**Comment by unsound** [comment]
No response so I closed it. Please provide more info for it to be reopened.
