### ISSUE TITLE
GiB vs. GB consistency

### ISSUE THREAD

**Issue by OlsonDev** [unsound/hfsexplorer#2]
The application should have consistent units. If you insist on using GiB, use it everywhere!

My personal opinion... use the kibi, mebi, gibi, etc.

**Comment by unsound** [comment]
Could you please give me an example of where this inconsistency exists? It's quite possible that I've been sloppy though I try to use the binary (gibi, etc.) prefixes wherever I can

**Comment by OlsonDev** [comment]
My bad, actually. You commented before I could close this issue. When I filed #1, I could've sworn I saw `GB` in the grid but evidently the `i` is just too small. Moments later, I realized I got ahead of myself. :-P
