### ISSUE TITLE
Extract data problem when using MacJapanese encoding due to out-of-range characters included in filenames

### ISSUE THREAD

**Issue by gingerbeardman** [unsound/hfsexplorer#26]
Reproduce:
1. load this ISO https://archive.org/details/cd-rom-maclife-31
2. set encoding to MacJapanese
3. right click root node
4. choose "Export data"

Screenshot
<img width="1013" alt="Screen shot 2021-10-26 at 13 49 53" src="https://user-images.githubusercontent.com/49612/138882188-ea5e130f-d3c0-41af-ac26-51a8663fc50c.png">

Note:
- if the encoding is set to MacRoman the export works, but the filenames are incomprehensible
- classic Mac OS System 7 does not complain about these discs/filenames

Another ISO that has the same problem
- https://archive.org/details/nikkei-mac-cd-rom-1994-2-17

An example that can be exported OK in MacJapanese
- https://archive.org/details/cd-rom-maclife-34

Aside:
- could this disc be using something not quite MacJapanese? 
  (I read that there are [several variations](https://developer.apple.com/documentation/coreservices/1399915-encoding_variants_for_macjapanes) but maybe it's something more than that)
- I believe this is the reason same reason I can't get good text dumps of the directory listings from `hfsutils`

**Comment by gingerbeardman** [comment]
it looks like there are some Shift-JIS characters in these "MacJapanese" discs too 😩

- 0xf052
- 0xfb43
- 0xfbe0

From ftp://ftp.unicode.org/Public/MAPPINGS/VENDORS/APPLE/JAPANESE.TXT

> - A user-defined range using Shift-JIS code points
>   0xF040-0xFCFC, providing 2444 code points.

**Comment by unsound** [comment]
This is an omission, I guess I assumed the table would cover all the mapped code points but you have to read the comments carefully as well:
```
# 1. Mapping the user-defined range
#
#    The table below covers only the standard Mac OS Japanese encoding.
#    It does not include mappings for the Shift-JIS user-defined range;
#    this is mapped onto Unicodes 0xE000-0xE98B as follows:
#      0xF040-0xF07E -> 0xE000-0xE03E
#      0xF080-0xF0FC -> 0xE03F-0xE0BB
#      0xF140-0xF17E -> 0xE0BC-0xE0FA
#      0xF180-0xF1FC -> 0xE0FB-0xE177
#      ...
#      0xFC40-0xFC7E -> 0xE8D0-0xE90E
#      0xFC80-0xFCFC -> 0xE90F-0xE98B
```

**Comment by unsound** [comment]
@gingerbeardman I pushed some fixes earlier today, please check if they improve things for your images.

**Comment by gingerbeardman** [comment]
Thanks, that's much improved!

A few oddities:

- 0x8559
- 0x866d
- 0x8770

These point to the symbols/dingbats block of Shift-JIS, but there are no characters at this specific locations. No idea what should be done with those.

**Comment by unsound** [comment]
Java's own Shift-JIS implementation fails to decode those, but `iconv` has possible matches:
```
$ printf "\x85\x59\n\x86\x6d\n\x87\x70\n" | iconv -f 'SHIFT_JISX0213' -t 'UTF-8'
Ã
ɚ̀
㎝
```

I just don't know where those matches come from...

**Comment by gingerbeardman** [comment]
It's a mystery. 

Classic Macintosh System 7 displays them as unknown character glyphs. 

...I'm wondering if the repeated digits could be mastering errors? So they'd be more like:

- 0x859?
- 0x86d?
- 0x870?

Just a thought.

**Comment by unsound** [comment]
Well... I can't imagine how that kind of error would have been introduced because it effectively would have mirrored the least significant 4-bit part of the previous byte into the most significant 4-bit part of the next byte, effectively shifting the high 4 bits to the low 4 bits of that byte. It just doesn't follow any logical error pattern that I've ever seen.

**Comment by gingerbeardman** [comment]
Interesting update: I found that `Tcl`'s encoding functions include MacJapanese (as "macJapan") and it deals with all of this without a single issue. 

https://gist.github.com/gingerbeardman/4a3b66236e018b72b32ca17953474e12

```sh
$ hls -1ablRN > file.txt
$ ./mac2unicode.tcl file.txt
```

So I thought you might want to look into how Tcl does things.

**Comment by gingerbeardman** [comment]
Closer inspection seems to show Tcl doesn't get it all correct, it just fails silently.

**Comment by unsound** [comment]
Alright then I think we have exhausted all possibilities for now to try and decode those sequences. I'm closing this but feel free to reopen if you think there's anything that can be improved here.

**Comment by gingerbeardman** [comment]
That's fine by me.

All that remains is for me to say _thank you_ for your attention and assistance on this.

**Comment by gingerbeardman** [comment]
Tcl uses the following Apple technique https://opensource.apple.com/source/tcl/tcl-10/tcl/tools/encoding/macJapan.txt 

It gets it all correct as long as you operate in binary mode (which I was neglecting to do yesterday)

**Comment by unsound** [comment]
@gingerbeardman So TCL does find matches for `0x8559`, `0x866d` and `0x8770`? I don't see any of those in the `macJapan.txt` table that you linked above.
What Unicode code points does it map those sequences to? (Decoding to UTF-32 should yield the exact Unicode code points.)

**Comment by gingerbeardman** [comment]
Good question! Of course I should have made a note which discs had those bytes. It took a while to find them again.

By "correct" I mean "it processes non-Japanese characters without error (and probably incorrectly)" but all Japanese characters appear as expected.

> Tcl just added a new encoding for me (based on the Apple/Unicode file JAPANESE.TXT which is subtly different to the existing macJapan.txt) but I'm yet to test this. I will when I figure out where/how to get the current Tcl source commits.

Looking into these byte combinations they seem to be non-Japanese characters.

The existing macJapan Tcl encoding deals with them as follows:

**0x8559**
- disc: MACLIFE04.ISO
- Tcl encoding: 0xC285 (0000 246B 0000 0085)
- filename: `41 半角⑧⑫\0x8559⑬→ 全角用`
- correct encoding scheme: ?
- screenshot: shown as "unknown glyph rectangle"
  <img width="187" alt="Screen shot 2021-11-16 at 16 51 58" src="https://user-images.githubusercontent.com/49612/142042247-c30d7499-c7b3-4804-952a-fb0cc5999f62.png">

**0x866d**
- disc: HYPERLIB-1994-1-CD2.ISO
- filename: `Ümlåût Õmêléttè`
- Tcl macJapan encoding: 0xC286 (0000 FEFF 0000 0086)
- correct encoding scheme: macRoman
- screenshot: ![Untitled](https://user-images.githubusercontent.com/49612/142040757-d849575f-8985-4e7b-97d5-b5f50577a0f1.png)

**0x8770**
- disc: MACBIN29.ISO
- filename: `Introducción rápida`
- Tcl encoding: 0xC287 (0000 0087)
- correct encoding scheme: macRoman
- screenshot:
  <img width="189" alt="Screen shot 2021-11-16 at 18 30 57" src="https://user-images.githubusercontent.com/49612/142044607-bde7b2ea-2ab7-40ef-af7b-e46a0c82dd7d.png">

## Supporting Files
[files.zip](https://github.com/unsound/hfsexplorer/files/7549085/files.zip)
1. full RAW bytes output of hfsutils' hls command
1. trimmed RAW bytes output of hfsutils' hls command
1. UTF-8 generated by Tcl encoding encodefrom
1. UTF-32 generated by iconv of above

**Comment by gingerbeardman** [comment]
Using https://github.com/gingerbeardman/encodings-tool I generated a list of what 0x8559 is in all supported encodings on modern macOS:

`BYTES=\`cat 8559.bin\`; encodings $BYTES | grep -v "null" > encodings-not-null-0x8559.txt`

[encodings-not-null-0x8559.txt](https://github.com/unsound/hfsexplorer/files/7549397/encodings-not-null-0x8559.txt)

Not much help but worth a try.

**Comment by gingerbeardman** [comment]
Just seen this screenshot in the wild on a Japanese for sale site. Thought you might like to see it!?

Screenshot of a screenshot:
![image](https://user-images.githubusercontent.com/49612/183297134-37d4ddaf-190f-4d15-9a73-5c1f8738c200.png)
