### ISSUE TITLE
Update web page to mention use on macOS 10.15 and later

### ISSUE THREAD

**Issue by ryandesign** [unsound/hfsexplorer#34]
The web page says:

> Linux and OS X users should in most cases not need HFSExplorer for browsing file systems on devices, since there are native file system drivers available on those systems, but it seems to work fine if you need it. 

macOS 10.15 (Catalina) removed support for HFS volumes, so there is a use for HFSExplorer on macOS 10.15 and later. You may want to update the web page to mention this.

**Comment by melMass** [comment]
> macOS 10.15 (Catalina) removed support for HFS volumes, so there is a use for HFSExplorer on macOS 10.15 and later. You may want to update the web page to mention this.

They definitely did not.... I use HFS in Monterey.

**Comment by ryandesign** [comment]
> They definitely did not....

They definitely did.

"[Apple discontinued support for classic HFS](https://www.matthewhughes.co.uk/how-to-mount-hfs-classic-drives-on-macos-catalina-and-later/) (also known as Mac OS Standard) volumes in MacOS 10.15 Catalina."

"Starting with macOS 10.15, [HFS disks can no longer be read](https://en.wikipedia.org/wiki/Hierarchical_File_System)."

> I use HFS in Monterey.

You definitely don't. You can still use HFS+ (Mac OS Extended), but not HFS (Mac OS Standard).

**Comment by melMass** [comment]
You are right, I missed you were referring to MacOS Standard, why do you need a 24years old obsolete file system?

**Comment by ryandesign** [comment]
My reasons for wanting to use this software aren't really relevant to this issue; people obviously have a desire to access HFS filesystems otherwise HFSExplorer would not exist. In my case, I have HFS disk images that I use with a classic Mac OS emulator; I might wish to use HFSExplorer to move data to or from those disk images. I also have some HFS CD-ROMs that I might want to read. I also have a USB floppy drive which I sometimes use to move data to or from a classic Mac.

**Comment by unsound** [comment]
Thanks for the suggestion. How about the following text instead (updating OS X to macOS as well):
> Linux and macOS users should in most cases not need HFSExplorer for browsing HFS+/HFSX (Mac OS Extended) file systems, since there are native file system drivers available on those systems, but it seems to work fine if you need it.
> Older HFS (Mac OS Standard) filesystems are supported by Linux and older macOS versions (up to and including macOS 10.14), but users of newer versions of macOS (10.15 and later) may find HFS support useful for browsing old disks and disk images.

**Comment by ryandesign** [comment]
Sounds good to me!

**Comment by unsound** [comment]
The text has been updated on the web site.
