### ISSUE TITLE
Help > Help browser does nothing

### ISSUE THREAD

**Issue by OlsonDev** [unsound/hfsexplorer#4]
Not sure if it matters but...
```
Windows 10 Pro Insider Preview Evaluation copy Build 10130
JRE 1.8.0_45
```

**Comment by unsound** [comment]
Should be fixed in 521b2e3c7f783022565f70652edc1ccb0afe2df7.

**Comment by OlsonDev** [comment]
I can confirm if I copy-paste the `doc` folder into the `bin` folder, functionality returns to the `Help browser` menu item.

Any plans on bumping the version / releasing an updated build?

**Comment by unsound** [comment]
Closing this issue even though you didn't actually test the fix. I'm confident it is going to be sufficient.
