### ISSUE TITLE
Feature request: drag and drop images into HFSExplorer to open them

### ISSUE THREAD

**Issue by zhuowei** [unsound/hfsexplorer#7]
When a .dmg is dragged and dropped into HFSExplorer 0.23, nothing happens. Tested on Windows 10 and Ubuntu Linux 14.04.

I know Swing on Java 7 [supports drag and dropped items](https://stackoverflow.com/questions/811248/how-can-i-use-drag-and-drop-in-swing-to-get-file-path), which would make opening .dmgs much more convenient - is this something that you're interested in adding/merging pull requests that adds this?

**Comment by unsound** [comment]
I just added this functionality to the `proposed` branch, exact commit `af6863d3`. Please check it out to make sure it solves your problem.
